function createEnum<T extends {[P in keyof T]: P}>(o: T) {
	return o;
}
export const ROUTE_KEY = createEnum({
	Splash: 'Splash',
	BottomTab: 'BottomTab',
	Login: 'Login',
	Onboarding: 'Onboarding',
	SignUp: 'SignUp',
	SignUpServices: 'SignUpServices',
	ForgotPass: 'ForgotPass',
	Otp: 'Otp',
	Search: 'Search',
	DetailService: 'DetailService',
	Booking: 'Booking',
	InfoServicer: 'InfoServicer',
	AllReview: 'AllReview',
	DetailNotification: 'DetailNotification',
	ChangePassword: 'ChangePassword',
	Setting: 'Setting',
	Term: 'Term',
	UpdateInformation: 'UpdateInformation',
	ListAddress: 'ListAddress',
	ChangePasswordForgot: 'ChangePasswordForgot',
	DetailOrder: 'DetailOrder',
	AddService: 'AddService',
	AcceptServicer: 'AcceptServicer',
	InfoAcceptServicer: 'InfoAcceptServicer',
	ManageServicer: 'ManageServicer',
	InfoDetailServicer: 'InfoDetailServicer',
	ManageUser: 'ManageUser',
	InfoDetailUser: 'InfoDetailUser',
	AddCategory: 'AddCategory',
	AddServiceCategory: 'AddServiceCategory',
	Payment: 'Payment',
	EditPaymentFee: 'EditPaymentFee',
	AddPayment: 'AddPayment',
});
