export const EN = {
	BottomTab: {},
	Onboarding: {},
	Otp: {},
	Home: {},
	Notification: {},
	Order: {},
	User: {
		title: 'PROFILE',
		activityStatusText: 'Activity Status',
		updateInfoButtonText: 'Update Information',
		addressButtonText: 'Address',
		changePasswordButtonText: 'Change Password',
		feeServiceText: 'Service Fee: ',
		blockedUsersButtonText: 'Blocked Users List',
		otherInfoText: 'OTHER INFORMATION',
		termsButtonText: 'Terms and Conditions',
		privacyPolicyButtonText: 'Privacy Policy',
		faqsButtonText: 'FAQs',
		settingsButtonText: 'Settings',
		logoutButtonText: 'Logout',
		logoutConfirmationMessage: 'Are you sure you want to log out?',
		unpaid: 'Unpaid',
		paid: 'Paid',
		wait: 'Awaiting Approval',
		ACCOUNT_MANAGEMENT: 'ACCOUNT MANAGEMENT',
		SERVICE: 'SERVICES',
	},
	Search: {},
	DetailService: {},
	Booking: {},
	InfoServicer: {},
	AllReview: {},
	DetailNotification: {},
	ChangePassword: {},
	Setting: {
		title: 'SETTING',
		listLanguage: ['Vietnamese', 'English', 'Chinese', 'Japanese', 'Korean'],
		Language: 'Language',
	},
	Term: {},
	UpdateInformation: {},
	ListAddress: {},
	ChangePasswordForgot: {},
	DetailOrder: {},
	AddService: {},
	AcceptServicer: {},
	InfoAcceptServicer: {},
	ManageServicer: {},
	InfoDetailServicer: {},
	ManageUser: {},
	InfoDetailUser: {},
	AddCategory: {},
	AddServiceCategory: {},
	Payment: {},
	EditPaymentFee: {},
	AddPayment: {},
	EvaluateService: {},
	ListUserBlock: {},
	FeeService: {},
	ManagePayment: {},
	AddressServicer: {},
	Policy: {},
	FAQ: {},
};
