export const KO = {
	BottomTab: {},
	Onboarding: {},
	Otp: {},
	Home: {},
	Notification: {},
	Order: {},
	User: {
		title: '프로필',
		activityStatusText: '활동 상태',
		updateInfoButtonText: '정보 업데이트',
		addressButtonText: '주소',
		changePasswordButtonText: '비밀번호 변경',
		feeServiceText: '서비스 수수료: ',
		blockedUsersButtonText: '차단된 사용자 목록',
		otherInfoText: '기타 정보',
		termsButtonText: '이용 약관',
		privacyPolicyButtonText: '개인 정보 보호 정책',
		faqsButtonText: '자주 묻는 질문',
		settingsButtonText: '설정',
		logoutButtonText: '로그아웃',
		logoutConfirmationMessage: '정말 로그아웃 하시겠습니까?',
		unpaid: '미결제',
		paid: '결제 완료',
		wait: '승인 대기 중',
		ACCOUNT_MANAGEMENT: '계정 관리',
		SERVICE: '서비스',
	},
	Search: {},
	DetailService: {},
	Booking: {},
	InfoServicer: {},
	AllReview: {},
	DetailNotification: {},
	ChangePassword: {},
	Setting: {
		title: '설정',
		listLanguage: ['베트남어', '영어', '중국어', '일본어', '한국어'],
		Language: '言語',
	},
	Term: {},
	UpdateInformation: {},
	ListAddress: {},
	ChangePasswordForgot: {},
	DetailOrder: {},
	AddService: {},
	AcceptServicer: {},
	InfoAcceptServicer: {},
	ManageServicer: {},
	InfoDetailServicer: {},
	ManageUser: {},
	InfoDetailUser: {},
	AddCategory: {},
	AddServiceCategory: {},
	Payment: {},
	EditPaymentFee: {},
	AddPayment: {},
	EvaluateService: {},
	ListUserBlock: {},
	FeeService: {},
	ManagePayment: {},
	AddressServicer: {},
	Policy: {},
	FAQ: {},
};
